import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/folder">폴더 페이지</Link>
        <br />
        <Link href="/shared">공유 페이지</Link>
        <br />
        <Link href="/signin">로그인 페이지</Link>
        <br />
        <Link href="/signup">회원가입 페이지</Link>
        <br />
      </main>
    </>
  );
}
